### ISSUE TITLE
Debug issue

### ISSUE THREAD

**Issue by kylewolfe** [sirnewton01/godev#10]
I had the debugger working yesterday. Not sure what changed but now I am getting this pop up when running execute in the debug window on a working helloworld.go project:

POST:{"Severity":"Error","HttpCode":400,"Message":"Error installing command.","DetailedMessage":"exit status 2"}

**Comment by sirnewton01** [comment]
The message is not as clear as it could be. The likely cause is that you have a compile error in your code.

Can you try a "go install helloworkpackage" command on your command prompt and confirm?

**Comment by sirnewton01** [comment]
I have pushed a change to the error message to make it a little more clear. Please re-open if the problem is something different.
