### ISSUE TITLE
Integrate kill into debug

### ISSUE THREAD

**Issue by kylewolfe** [sirnewton01/godev#12]
Would it be possible to add ability to kill a process that was started from the debug panel? I just started developing a web app and have to manually kill the process from command line.

**Comment by kylewolfe** [comment]
Just found stop at bottom right.

**Comment by sirnewton01** [comment]
Yes, I hit this while trying to debug godev itself in the past. I could move the "Stop" button up to the left pane to make it more obvious. There are definitely limits to the capabilities in that page. It's mostly just to be able to launch and remember the command-line parameters at the moment.
