### ISSUE TITLE
Syntax highlighter chokes on raw strings

### ISSUE THREAD

**Issue by the42** [sirnewton01/godev#14]
After a line like that

```
        case "resource_format":
            const checkchars = `.:/\`
```

syntax highlighting stops.

![check go_-_editor_-_2014-01-13_21 45 46](https://f.cloud.github.com/assets/160382/1904686/c48448e2-7c93-11e3-9695-3c8439e194aa.png)

**Comment by sirnewton01** [comment]
Thank you for raising the problem.

Does the problem go away if you reload the browser page?

I am looking at revamping the syntax highlighter for the next sprint. Hopefully, it will be a bit more robust and faster when I'm finished.

**Comment by the42** [comment]
No, reloading doesn't help, even after clearing cache.

**Comment by sirnewton01** [comment]
Thanks, I believe I have discovered the cause of the problem. I have been working on a new syntax highlighter that should be available after the next sprint.

**Comment by sirnewton01** [comment]
The new highlighter has been pushed to github. I tested it with multi-line strings like the one you have above and I believe it works better now.

go get -u github.com/sirnewton01/godev

**Comment by the42** [comment]
Syntax highlighting works but for the first file to edit.

The fist file clicked to edit receives no syntax highlighting. Actually another issue.

**Comment by sirnewton01** [comment]
Just to clarify, only the first file you open gets the syntax highlighting? When you click on other files there's no highlighting?

Which web browser are you using and what's the version on it?

Thanks,
Chris

**Comment by the42** [comment]
Sorry for being imprecise, it's the other way round. The first file I visit doesn't get highlighted, every other file I open is now properly syntax highlighted. Interestingly F5 doesn't make to problem disappear, I have to open another file. Using FF 26 on Linux.

**Comment by sirnewton01** [comment]
I tried it with my Firefox 26 on Linux and I saw a slight delay on the first file but then it showed up.

Is it possible that it is always the same file that doesn't show the highlighting?

Can you try clearing out your browser cache and see if that fixes it? History->Clear Recent History...

Otherwise, can you check out the firefox javascript console to see if there are any errors shown in there? Ctrl-Shift-K

Thanks for helping me to narrow down the problem,
Chris

**Comment by the42** [comment]
After clearing the cache, Highlighting works immediately. Sorry for the noise.

**Comment by sirnewton01** [comment]
Thanks for following up with this. It looks like I need to recommend that everyone clears their browser cache after upgrading godev or reporting bugs.
