### ISSUE TITLE
Syntax highlighting gone (and ability to use most external commads, eg gofmt)

### ISSUE THREAD

**Issue by ifross89** [sirnewton01/godev#15]
I got godev up and running yesterday and everything worked great.

I tried to use it again today but all syntax highlighting had gone, as well as the ability to use external commands (apart from blame). This means I cannot use gofmt, oracle, etc.

See the following picture:
![godev_issue](https://f.cloud.github.com/assets/3983918/1932177/d7600262-7ec8-11e3-9ef2-e1ef6607fc46.png)

**Comment by sirnewton01** [comment]
Hi,

Thank you for raising this issue. It appears that some of the internal modules are not loading properly.

Can you try this set of steps to see if the "Go Language Core Plugin" and "Orion CodeMirror syntax highlighting" are working:

1) Click on the icon on the top-right corner of your godev page
2) Pick the "Plugins" section on the left side of the settings page
3) Click the "Reload All" button on the top-right of the plugins section
4) Check that the two modules listed above are there and don't report any errors

Also, you can try reset your browser's cache. On Chrome you can do this with the menu->Tools->Clear Browsing Data... For Firefox, this is done through the History menu.

If none of this is helping to resolve the problem can you open up the developer tools for your browser and see if there is anything in the JavaScript console?

Chris

**Comment by ifross89** [comment]
Reloading the plugins seemed to fix the issue!

Thanks for your help.

**Comment by sirnewton01** [comment]
I'm glad to hear that it's working again for you.

Cheers,
Chris
