### ISSUE TITLE
Proposal: additional "stupid" word completion

### ISSUE THREAD

**Issue by akavel** [sirnewton01/godev#21]
I would like also to suggest, if you could consider, adding a "stupid" word completion, based on all words occurring in a file. I longed for such when writing "top-down" code, i.e. first writing high level function with names of not-yet-existant low-level functions, and then trying to fill them with body. When I then tried to write function prototypes, I could not use completion, and had to either rewrite from memory, or search for the callsite and only then be able to copy&paste.

Thanks!

**Comment by sirnewton01** [comment]
This is an interesting suggestion. If I understand correctly you want to be able to do something like this:

func myfunc() {
     someOtherFunc("foo")

```
 if true {
      someOther<Ctrl-Space>
 }
```

}

And have "someOtherFunc" show up as a suggestion even though you have not yet defined it?

Godev actually uses a popular content assist for Go called "gocode." It has vi and emacs support as well. I think this suggestion could benefit everyone if it were implemented inside gocode itself. Perhaps you can raise this enhancement there?

https://github.com/nsf/gocode

Thanks,
Chris

**Comment by sirnewton01** [comment]
I'm going to close this for now. Please raise this against the github.com/nsf/gocode project if you're still interested in it.
