### ISSUE TITLE
Run external tools without PATH?

### ISSUE THREAD

**Issue by viblo** [sirnewton01/godev#22]
I usually dont setup my PATH to include the $GOPATH/bin folder. This caused some confusion when I tried to run some of the external tools like godef, because godev only said in the error that I should go get godef. However that did not make it work because it expect that the godef binary is on my PATH but its not.

The easiest for me would be if it could check for the tools in $GOPATH/bin if not found in PATH. But if that not possible please at least mention it in the in the readme :)

If you update the readme please also add that you need to go install the tools as well, not just go get them. It is not totally obvious that you need that now (at first I assumed that godev itself would install them after I go getted them)

**Comment by sirnewton01** [comment]
Thank you for raising this problem.

I will update the README to provide more details about the expected environment.

I am fairly certain that "go get" should install the package as well. Here's an excerpt from the "go get" docs:

"Get downloads and _installs_ the packages named by the import paths,
along with their dependencies."

Perhaps there is something going wrong with your Go installation?

**Comment by viblo** [comment]
Ah, ofc! go get works as expected on my machine as well, dont know what I was thinking when I wrote it in the first post!

**Comment by sirnewton01** [comment]
This will be fixed next time I push to github. Closing it for now.
