### ISSUE TITLE
std packages

### ISSUE THREAD

**Issue by rhedile** [sirnewton01/godev#24]
why is this necessary?
go get -u github.com/sirnewton01/godev
go install unicode/utf8: open /usr/local/go/pkg/linux_386/unicode/utf8.a: permission denied
go install hash: open /usr/local/go/pkg/linux_386/hash.a: permission denied
go install crypto/cipher: open /usr/local/go/pkg/linux_386/crypto/cipher.a: permission denied
go install crypto/subtle: open /usr/local/go/pkg/linux_386/crypto/subtle.a: permission denied
go install unicode/utf16: open /usr/local/go/pkg/linux_386/unicode/utf16.a: permission denied
go install unicode: open /usr/local/go/pkg/linux_386/unicode.a: permission denied

**Comment by shirro** [comment]
It looks to me like your go installation is broken and goget is trying to resolve dependencies by compiling standard libraries that are missing from your GOROOT.

**Comment by rhedile** [comment]
Thanks for the reply, but my go installation is working fine, and so did
godev until trying to update.

 ls -la /usr/local/go/pkg/linux_386/unicode
insgesamt 44
drwxr-xr-x  2 root root  4096 Jan 14 14:10 .
drwxr-xr-x 27 root root  4096 Feb 25 15:15 ..
-rw-r--r--  1 root root 10110 Aug 13  2013 utf16.a
-rw-r--r--  1 root root 22306 Aug 13  2013 utf8.a

I shall have to look deeper.

**Comment by dmitshur** [comment]
I tried it just now, and I had no issues. It does sound like there's something up with your Go install.

``` bash
$ go version
go version go1.2.1 darwin/amd64
$ go get -u github.com/sirnewton01/godev
$ 
```

**Comment by rhedile** [comment]
Sorry can't use 1.2.x(heap?!). Ubuntu 12.04 LTS Server. This is 1.1.2. It has a heavily extended net/textproto & net/smtp and go is rebuilt daily. If I force an install -a std it rebuilds the unicode/*.a giving:
ls -la /usr/local/go/pkg/linux_386/unicode
insgesamt 44
drwxr-xr-x  2 root root  4096 Mär  5 06:10 .
drwxr-xr-x 27 root root  4096 Mär  5 06:10 ..
-rw-r--r--  1 root root 10100 Mär  5 06:10 utf16.a
-rw-r--r--  1 root root 22296 Mär  5 06:10 utf8.a
Subsequently godev installs without error but has unconnected runtime issues. Why there suddenly a 10 byte difference in utf8.a with the standard package, I can't answer at the moment.  I would make the point that a third party package trying to rebuild our std would fail on permissions. The question is why it failed when the source is unchanged. Still looking.

**Comment by sirnewton01** [comment]
I'm unclear how these problems are related to godev. Can you clarify?

**Comment by rhedile** [comment]
Go is our primary development language. We have some 40000 lines of code in an InHouse Application. One of our biggest concerns is corruption by a malicious/broken 3 party application/library. We may be paranoid but we don't understand  why an update to godev should try to reinstall STD packages as indicated in the original post. There is only one person in house who is allowed to rebuild std and he has to take a snapshot before he does so. On pain of death stuff. We don't use your package in development. It was installed to help somebody from "compliance", a lawyer/DBA,  periodically check the database types. He only has read permissions on /src. In the installed version there were security concerns. The updated version would have addressed some of these concerns. 

With alarm bells ringing all over the place and compliance bugging everyone, the developer who tried the update is still a little incoherent. 

At the moment godev is guilty by association and our original question is unanswered. 

-We have checked our own local repository and there is no compromise of the standard packages.
-There is also no compromise of our own packages.
-The only code modifications in the timeframe were the update of godev.
These changes were casually reviewed yesterday. There was nothing out of the ordinary.

We have a snapshot of the developer machine taken 2 hrs before the update attempt. We will use it to replay the developers bash history from the production machine. When the FMTA is completed, we should know more about what happened.

**Comment by sirnewton01** [comment]
Please let me know if you find that there's a problem in godev and I'll gladly make a fix.

**Comment by rhedile** [comment]
We have now played this through twice. The results are at the moment inconclusive. The moment a go build on the godev update is called the installed std packages are ignored, and the reinstall fails because of lack of permissions. At this point this is correct.  It's really wierd, strace is not seeing problems finding the std packages, umask is standard. All other local packages are rebuilding correctly against the installed packages including a https proxy using crypto. We currently following two lines of thought. We are checking the individual import paths in godev with go builds' "stats". We are also checking the go tools for missing errors. If we are unable to close this today we not be able to continue until Wednesday 1400 CET.

**Comment by sirnewton01** [comment]
I'm going to close this for now. Please re-open it if there's anything that I can do to fix godev. Thanks.
