### ISSUE TITLE
missing Tools in menu bar

### ISSUE THREAD

**Issue by n-riesco** [sirnewton01/godev#27]
Sometimes I stop seeing Tools in the menu bar. To get it back, I have to go to godoc and then come back to the workspace.

**Comment by sirnewton01** [comment]
Thanks for raising the issue.

What web browser are you using? Have you tried the troubleshooting steps in the README.md?

**Comment by n-riesco** [comment]
I'm sorry I can't reproduce the issue.

I've checked it works with firefox (using private browsing) and chromium 
(using a temporary profile).

Another explanation could be that I got confused by Tools disappearing 
from the menu bar whenever I click on a folder.

Sorry about the noise and thanks for godev.
