### ISSUE TITLE
Direction on using GOHOST, GOKEYFILE, GOCERTFILE

### ISSUE THREAD

**Issue by equalunique** [sirnewton01/godev#29]
I noticed these variables in godev.go and started wondering if this is how HTTPS is supposed to be set up. Is there any basic guidance on how to utilize this?

Awesome project btw!

**Comment by sirnewton01** [comment]
@erowley check out the section called "Remote Access" in the README.md for details on how to set up remote access. It explains the different environment variables. If you encounter any problems or the documentation isn't clear please re-open this issue.
