### ISSUE TITLE
Symlink support in directory pane

### ISSUE THREAD

**Issue by intel352** [sirnewton01/godev#4]
I have a bitbucket repo cloned in one location, while my workspace has a symlink to the clone.

If I browse to the symlink in GoDev, the left pane shows the symlink as if it's a file. If I click on the symlink, I see a browsable directory in the right pane.

I'd like to see the left pane act as if the symlink is a folder directly (at least for a symlink that points to a folder). Doable?

**Comment by sirnewton01** [comment]
Thank you for raising this issue.

I think it should be pretty easy to do. Now that you've raised it I'll have a look.

Are you using Windows symlinks or Linux ones?

**Comment by intel352** [comment]
I'm on OSX, so *nix-based symlinks

**Comment by sirnewton01** [comment]
I have opened a defect for this on JazzHub, which I use for my planning:
https://hub.jazz.net/ccm01/web/projects/sirnewton%20%7C%20godev#action=com.ibm.team.workitem.viewWorkItem&id=8630

**Comment by sirnewton01** [comment]
I have pushed changes that should fix the symbolic link handling. Can you give it a try again after doing a "go get -u github.com/sirnewton01/godev"

Thanks,
Chris
