### ISSUE TITLE
Keep opened files along the top as tabs

### ISSUE THREAD

**Issue by intel352** [sirnewton01/godev#5]
One thing I miss from standard IDEs is how opened files are still available in a tabbed view, so I can flit among the tabs as needed. It would be nice to have a similar functionality added to godev.

**Comment by sirnewton01** [comment]
The general philosophy is that the web browser manages the different tabs, history, navigation, etc.

Would Ctrl-Tab provide the functionality that you are looking for? Also, firefox's awesome bar will try to match the title of open tabs as you type and allow you to flip to it quickly.

**Comment by intel352** [comment]
That approach will have to suffice then, tho I will miss the ability from full-fledged IDEs of being able to have two files open (or the same file open) in two panes, to be able to edit one section of code while referring to another.
I can partially mimic that behavior on Win7 (using the "snap" feature to size windows to left or right portion of screen) or OSX using Cinch (mimic's that Win7 snap function), but being able to have tiles that are horizontal rather than vertical is still missing (one stacked over the other).

Does godev/orion support live updating of the file browser (left pane) and open files, if there are modifications that occur on the filesystem (i.e. - via another godev tab)?

**Comment by sirnewton01** [comment]
Thanks for the feedback.

Split editors would be great to have. Your workarounds sound good too. Hopefully you'll find that the web browser provides alot of navigation and history capabilities to make up for some of its shortcomings.

The navigator on the left doesn't refresh very often and can sometimes go a bit stale. The editors should be capable of checking for changes to the file contents when you flip between tabs. It should also manage the case where you haven't saved the buffer and ask whether you want the contents on disk or to keep the buffer in memory.
