### ISSUE TITLE
links under "Go Test" are not navigable on windows

### ISSUE THREAD

**Issue by shivakumargn** [sirnewton01/godev#7]
On windows, after executing tests via the UI, the resulting link is as below (note the back-slash)

http://localhost:2022/edit/edit.html#\file\xyz\xyz_test.go,line=12

The link is not navigable.

**Comment by shivakumargn** [comment]
This issue exists for other cases as well - Ex:build error indicator - in attached image build error is in the currently opened file but editor thinks it is in some other file.

![godev_build_error](https://f.cloud.github.com/assets/171191/1628461/86c51500-5712-11e3-849e-eb10d0bdf8a6.png)

**Comment by sirnewton01** [comment]
Thank you for reporting these. I hope to have a look on a Windows VM and have fixes for the problems shortly.

**Comment by sirnewton01** [comment]
Thank you for the proposed fix. I have merged and pushed this to github. You can "go get -u github.com/sirnewton01/godev" to get the latest version.
