### ISSUE TITLE
editing binaries...

### ISSUE THREAD

**Issue by kristofer** [sirnewton01/godev#9]
so yes I got it running, but when I open a binary, it opens in the editor (which is good or bad) but I'm sure the IDE should open a binary...
comments?

**Comment by sirnewton01** [comment]
Hi,

There is a binary file in your gopath and when you click on it the editor opens it up showing garbage characters?

I have seen this before. It doesn't cause too much trouble as long as the file isn't really big. Would you prefer that it shows a message indicating it is binary without opening it?

Thanks,
Chris

**Comment by sirnewton01** [comment]
Opening binary files using godev is not recommended. Please re-open if you think that there should be better safeguards against opening binaries.
